### ISSUE TITLE
stl-to-voxel and EMpy conflicting

### ISSUE THREAD

**Issue by vahid-ax** [paulxshen/Luminescent.jl#44]
Hi Paul, I am trying to install it for the first time. 
Using conda + python 3.12.8.

issue 1 : I had to manually "pip install sortedcontainers stl-to-voxel" because they were missing dependencies. And stl-to-voxel forces numpy<2.0.

issue 2: Then when trying your simple example, it cannot find EMpy, see image. And EMpy needs numpy>2.0. So I am stuck!

![Screenshot 2024-12-17 at 11 05 20 PM](https://github.com/user-attachments/assets/d59b7f9d-5479-4a36-bda3-de660f841218)

**Comment by paulxshen** [comment]
Hi Vahid I'll patch the missing deps in next release. In meantime you can pip install ElectromagneticPython for EMpy (there's another package called empy which is different and may be causing the numpy issue)

**Comment by vahid-ax** [comment]
tnx! it's working

**Comment by paulxshen** [comment]
@vahid-ax Happy new years! I made significant gpu optimizations and setup now runs on linux. Will post new version in couple days.
